/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { CustomBlending, MultiplyBlending } from 'three';

export default function RecordModel({ normal, map, ...rest }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('assets/untitled.glb');
  console.log(materials);
  return (
    <group ref={group} {...rest} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube246.geometry}
        material={materials['Material.001']}
        rotation={[0, Math.PI / 2, 0]}
        // scale={[1, 1, 0.1]}
      />
    </group>
  );
}

useGLTF.preload('assets/untitled.glb');
